"""add_vr360_scenes_table

Revision ID: 36ddc74b5eef
Revises: 531fb09bb633
Create Date: 2026-05-13 08:55:47.050837

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '36ddc74b5eef'
down_revision = '531fb09bb633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vr360_scenes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('property_id', sa.Integer(), nullable=True),
        sa.Column('scene_id', sa.String(length=255), nullable=False),
        sa.Column('scene_name', sa.String(length=255), nullable=False),
        sa.Column('scene_subtitle', sa.String(length=500), nullable=True),
        sa.Column('display_order', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vr360_scenes_property_id'), 'vr360_scenes', ['property_id'], unique=False)
    op.create_index(op.f('ix_vr360_scenes_scene_id'), 'vr360_scenes', ['scene_id'], unique=False)
    op.create_index(op.f('ix_vr360_scenes_tenant_id'), 'vr360_scenes', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vr360_scenes_tenant_id'), table_name='vr360_scenes')
    op.drop_index(op.f('ix_vr360_scenes_scene_id'), table_name='vr360_scenes')
    op.drop_index(op.f('ix_vr360_scenes_property_id'), table_name='vr360_scenes')
    op.drop_table('vr360_scenes')
    # ### end Alembic commands ###
