services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - app-db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - .env.production
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - MYSQL_SERVER=db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://travel.link360.vn/api
        - NODE_ENV=production
    restart: always
    ports:
      - "3001:80"
    networks:
      - app-network

  prestart:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: "no"
    depends_on:
      - db
    command: bash scripts/prestart.sh
    env_file:
      - .env.production
    networks:
      - app-network
    environment:
      - MYSQL_SERVER=db

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8080"
    networks:
      - app-network

volumes:
  app-db-data:

networks:
  app-network:
    driver: bridge