version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - app-db-data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build:
      context: ./backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - backend-uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        - VITE_API_URL=http://localhost:8000
        - NODE_ENV=development
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8080"

  prestart:
    build:
      context: ./backend
    restart: "no"
    depends_on:
      - db
    command: bash scripts/prestart.sh
    env_file:
      - .env.production

volumes:
  app-db-data:
  backend-uploads:
